### ISSUE TITLE
app服务器运行不起来

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/im-app_server#13]
用h2没问题

用mysql就不行。报一堆错误

.java:243) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:2
14) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:176)
 ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:118) 
~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl
.java:1224) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.ja
va:1255) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFac
tory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(Loca
lContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEnt
ityManagerFactoryBean.java:391) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFac
toryBean.java:378) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEnti
tyManagerFactoryBean.java:341) ~[spring-orm-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractA
utowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAuto
wireCapableBeanFactory.java:1790) ~[spring-beans-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        ... 77 common frames omitted
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect
' not set
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:1
00) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:54) ~
[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator
.java:137) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator
.java:35) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistry
Impl.java:101) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.jav
a:263) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
        ... 94 common frames omitted

**Comment by mankind-evolve** [comment]
检查过mysql的账号密码 没啥问题啊

**Comment by mankind-evolve** [comment]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroConfig': Unsa
tisfied dependency expressed through field 'dbSessionDao'; nested exception is org.springframework.beans.factory.Un
satisfiedDependencyException: Error creating bean with name 'DBSessionDao': Unsatisfied dependency expressed throug
h field 'shiroSessionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Erro
r creating bean with name 'shiroSessionRepository': Cannot create inner bean '(inner bean)#3e96bacf' of type [org.s
pringframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#3e96bacf': Ca
nnot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.s
pringframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in
 class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation o
f init method failed; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested se
rvice [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]

**Comment by mankind-evolve** [comment]
版本号 0.47.1

**Comment by heavyrain2012** [comment]
数据库手工创建了吗

**Comment by mankind-evolve** [comment]
手工创建了。一个新库，链接也检查了好几遍

**Comment by heavyrain2012** [comment]
我们这边都是好的啊，好奇怪啊！你把控制台日志保存到一个文件中，还有服务的配置文件（只要mysql那部分），发送到support@wildfirechat.cn 我们看一下日志

**Comment by mankind-evolve** [comment]
已经发送了

**Comment by mankind-evolve** [comment]
有效
