### ISSUE TITLE
APP-Server运行不起来

### ISSUE THREAD

**Issue by JosserJiang** [wildfirechat/im-app_server#41]
下载野火的APP-Server最新版本，运行java -jar app-0.xx.jar后，报如下错误，这个错误应该如何改？

`SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/Josser/Desktop/APP_Server/app-0.67.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Josser/Desktop/APP_Server/app-0.67.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.17.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/Josser/Desktop/APP_Server/app-0.67.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.2.10.RELEASE)

2024-05-18 12:14:58.683  INFO 23296 --- [           main] cn.wildfirechat.app.Application          : Starting Application v0.67 on LAPTOP-TNPQOO19 with PID 23296 (C:\Users\Josser\Desktop\APP_Server\app-0.67.jar started by Josser in C:\Users\Josser)
2024-05-18 12:14:58.688  INFO 23296 --- [           main] cn.wildfirechat.app.Application          : No active profile set, falling back to default profiles: default
2024-05-18 12:14:59.185  WARN 23296 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [cn.wildfirechat.app.Application]; nested exception is java.io.FileNotFoundException: config\im.properties (绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆?

2024-05-18 12:14:59.853 ERROR 23296 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [cn.wildfirechat.app.Application]; nested exception is java.io.FileNotFoundException: config\im.properties (绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆?
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:189) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.10.RELEASE.jar!/:2.2.10.RELEASE]
        at cn.wildfirechat.app.Application.main(Application.java:24) ~[classes!/:0.67]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[app-0.67.jar:0.67]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[app-0.67.jar:0.67]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[app-0.67.jar:0.67]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[app-0.67.jar:0.67]
Caused by: java.io.FileNotFoundException: config\im.properties (绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆?
        at java.base/java.io.FileInputStream.open0(Native Method) ~[na:na]
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219) ~[na:na]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158) ~[na:na]
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112) ~[na:na]
        at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86) ~[na:na]
        at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189) ~[na:na]
        at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:186) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.EncodedResource.getReader(EncodedResource.java:143) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:95) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:73) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:59) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:67) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:37) ~[spring-core-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:463) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:280) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:304) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175) ~[spring-context-5.2.9.RELEASE.jar!/:5.2.9.RELEASE]
        ... 19 common frames omitted`

**Comment by imndx** [comment]
是不是没有配置文件，请参考

[本演示服务有4个配置文件在工程的config目录下，分别是application.properties, im.properties, aliyun_sms.properties和tencent_sms.properties。请正确配置放到jar包所在的目录下的config目录下。](https://github.com/wildfirechat/app-server?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE)

**Comment by JosserJiang** [comment]
> 是不是没有配置文件，请参考
> 
> [本演示服务有4个配置文件在工程的config目录下，分别是application.properties, im.properties, aliyun_sms.properties和tencent_sms.properties。请正确配置放到jar包所在的目录下的config目录下。](https://github.com/wildfirechat/app-server?tab=readme-ov-file#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE)

有配置文件，并且也是在您说的这个目录下面

**Comment by imndx** [comment]
你需要进入`app-0.xx.jar` 文件所在的目录执行：`java -jar app-0.xx.jar`，然后`config`和`app-0.xx.jar`是在同一个目录下

**Comment by JosserJiang** [comment]
感谢回复，命令窗口中确认要把路径切换到app-0.xx.jar目录下才有用
